### PR TITLE
20240219 soar release notes

### PR DESCRIPTION
**Pull request by fzampori**
## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [x] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Review by jpipkin1 — APPROVED** [review]
Looks good, @fzampori. I made some minor changes (see commit "[Updates from review](https://github.com/SumoLogic/sumologic-documentation/pull/3728/commits/5253c2672894e7e21993a18b7cb9cd188cddffb0)").

**Comment by fzampori** [comment]
Hi John, date was intended as production was updated on 19 February not sure why changing with 23rd 🤔

**Comment by fzampori** [comment]
I opened new pr to update it https://github.com/SumoLogic/sumologic-documentation/pull/3733

**Comment by jpipkin1** [comment]
My apologies, @fzampori. Our standard is to date release notes the day they are published.

**Pull request merged**
