### PR TITLE
SUMO-251499: Adding monitor's information to OTEL Apps Set1

### PR DESCRIPTION
**Pull request by chetanchoudhary-sumo**
## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Review by JV0812 — CHANGES_REQUESTED** [review]
@chetanchoudhary-sumo I have fixed the table title and added the word "Count" for the values in Alert condition and recover condition column. Can you please fix the same for rest of the tables?

**Review by JV0812 — APPROVED** [review]
LGTM

**Review by amee-sumo — APPROVED** [review]
LGTM

**Comment by jpipkin1** [comment]
@chetanchoudhary-sumo, can this PR be merged?

**Comment by chetanchoudhary-sumo** [comment]
> @chetanchoudhary-sumo, can this PR be merged?

Yes

**Pull request merged**
