### PR TITLE
Update metrics metadata limits audit logging

### PR DESCRIPTION
**Pull request by mfiglus**
## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by JainM6 — APPROVED** [review]
Approving as per the doc review parameters. SMEs must review the technical content.

Thanks,
Megha

**Review by michaljmatusiak92 — APPROVED** [review]
Should we also update the screenshots?

**Comment by mfiglus** [comment]
Screenshots should be still good enough

**Review by kimsauce — APPROVED** [review]

**Comment by kimsauce** [comment]
Hi @mfiglus , as per the above comment, [please sign our CLA](https://github.com/SumoLogic/sumologic-documentation/pull/870#issuecomment-1305308569) (required for all contributors). Thank you for your help with this doc!

**Pull request merged**
