### PR TITLE
Second instance FIPS 140-2

### PR DESCRIPTION
**Pull request by stacykor**
Second instance per @kimsauce  that FIPS 140-2 compliance is not available for Cloud Syslog in the FedRAMP deployment.

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by kimsauce — APPROVED** [review]

**Comment by kimsauce** [comment]
@stacykor , did you mean to edit the AWS GovCloud file here? The Cloud Syslog edit was handled in your [previous PR](https://github.com/SumoLogic/sumologic-documentation/pull/2172).

**Comment by kimsauce** [comment]
@stacykor, did you mean to edit the AWS GovCloud file in this PR? 

The Cloud Syslog edit you did here was handled in your https://github.com/SumoLogic/sumologic-documentation/pull/2172, so this PR is rendering as blank because the change was already done.

**Comment by stacykor** [comment]
> @stacykor, did you mean to edit the AWS GovCloud file in this PR?
> 
> The Cloud Syslog edit you did here was handled in your #2172, so this PR is rendering as blank because the change was already done.

I'll look in the morning. I was trying to grab the second instance.

**Comment by kimsauce** [comment]
@stacykor I will close this one out since it's not needed

**Pull request closed without merging**
