### PR TITLE
initial checkin for for nine new AWS specific doc-only app documentat…

### PR DESCRIPTION
**Pull request by npande**
…ion.

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by jpipkin1 — CHANGES_REQUESTED** [review]
@npande, thank you for submitting such a clean set of articles! They look very good. I have no comments or corrections on them.

Were you planning to add the new articles to the `/docs/integrations/amazon-aws/index.md` file that generates the following page? Or perhaps @JV0812 was planning to do that for you once all the new articles are added?
https://help.sumologic.com/docs/integrations/amazon-aws/

**Comment by jpipkin1** [comment]
FYI @JV0812, beginning with the [AWS API Gateway](https://help.sumologic.com/docs/integrations/amazon-aws/api-gateway/) article, the articles are not in alphabetical order in the [Amazon and AWS](https://help.sumologic.com/docs/integrations/amazon-aws/) section.

**Comment by npande** [comment]
> FYI @JV0812, beginning with the [AWS API Gateway](https://help.sumologic.com/docs/integrations/amazon-aws/api-gateway/) article, the articles are not in alphabetical order in the [Amazon and AWS](https://help.sumologic.com/docs/integrations/amazon-aws/) section.

Earlier it was decided to keep all doc-only apps at the top in sorted order followed by other apps in sorted order. I am ok with whatever docs team decide.

**Comment by JV0812** [comment]
> > @npande, thank you for submitting such a clean set of articles! They look very good. I have no comments or corrections on them.
> > Were you planning to add the new articles to the `/docs/integrations/amazon-aws/index.md` file that generates the following page? Or perhaps @JV0812 was planning to do that for you once all the new articles are added? https://help.sumologic.com/docs/integrations/amazon-aws/
> 
> We decided that @JV0812 will be handling the index

I will take care of the index page once all the related AWS integration docs are added.

**Comment by JV0812** [comment]
> > FYI @JV0812, beginning with the [AWS API Gateway](https://help.sumologic.com/docs/integrations/amazon-aws/api-gateway/) article, the articles are not in alphabetical order in the [Amazon and AWS](https://help.sumologic.com/docs/integrations/amazon-aws/) section.
> 
> Earlier it was decided to keep all doc-only apps at the top in sorted order followed by other apps in sorted order. I am ok with whatever docs team decide.

@jpipkin1 As per the discussion I had Stacy, we will go ahead by keeping all doc-only apps at the top in sorted order followed by other apps in sorted order. If we need to sort it with the existing app doc we can take it up sepeartely.

**Review by JV0812 — APPROVED** [review]
LGTM

**Review by jpipkin1 — APPROVED** [review]

**Pull request merged**
