### PR TITLE
API Gateway release notes

### PR DESCRIPTION
**Pull request by JV0812**
## Purpose of this pull request

This pull request is to create the release notes for the API Gateway app update.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

[Release notes for API Gateway](https://sumologic.atlassian.net/browse/SUMO-240929)

### CODE REVIEW

**Review by jpipkin1 — APPROVED** [review]
Looks good, @JV0812. I see in the [Jira ticket](https://sumologic.atlassian.net/browse/SUMO-240929) that the feature released on March 13, so this PR is finally publishing the release note for it.

**Review by kimsauce — COMMENTED** [review]
should the release date be 4/14 (or 4/15 local india time)?

**Comment by JV0812** [comment]
Yes @jpipkin1, we were waiting for the input from Greg and looks like the dev people got input for all at once and there are 5 more features that needs a release note.

**Comment by JV0812** [comment]
I guess we can publish the release note with the actual release date of the feature, so it should be 13-03-2024 (As per the JIRA ticket).

**Pull request merged**
