### PR TITLE
Update deletion-requests.md

### PR DESCRIPTION
**Pull request by JV0812**
## Purpose of this pull request

This pull request is to update the structure of the doc and update the example.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

[Update Deletion Requests doc](https://sumologic.atlassian.net/browse/DOCS-585)

### CODE REVIEW

**Review by jpipkin1 — APPROVED** [review]
Looks good, @JV0812.

**Review by rjury-sumo — APPROVED** [review]
LGTM

**Comment by kimsauce** [comment]
@JV0812 @manashar4 , is this related? https://github.com/SumoLogic/sumologic-documentation/pull/4500

**Comment by JV0812** [comment]
@kimsauce both are different tasks, but impacts the same doc. I will go ahead and merge this branch and will cover the changes related to limitations in the other PR which Manas has created. Thanks for looking into this!

**Comment by kimsauce** [comment]
> @kimsauce both are different tasks, but impacts the same doc. I will go ahead and merge this branch and will cover the changes related to limitations in the other PR which Manas has created. Thanks for looking into this!

you're the best!

**Pull request merged**
