### PR TITLE
Actions limit /reuse text

### PR DESCRIPTION
**Pull request by kimsauce**
## Purpose of this pull request

This pull request...

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Comment by jpipkin1** [comment]
@kimsauce, why did you change the name of the file from `action-limits.md` to `actions-limit.md`? Just so that it's named more accurately?

**Comment by kimsauce** [comment]
> @kimsauce, why did you change the name of the file from `action-limits.md` to `actions-limit.md`? Just so that it's named more accurately?

Yes - that and the anchor link was a little off. I came across this while editing something unrelated. Can you test this out when you have a chance?

**Review by jpipkin1 — APPROVED** [review]
Looks great, @kimsauce!

**Comment by kimsauce** [comment]
> Looks great, @kimsauce!

thank you!

**Pull request merged**
