### PR TITLE
CSE Administration Index

### PR DESCRIPTION
**Pull request by Melvin-CnC**
Made changes as per the Open Source Docs Migration Plan.

## Purpose of this pull request

This pull request (PR) to edit the CSE Administration Index page under Cloud SIEM.

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by jpipkin1 — CHANGES_REQUESTED** [review]
@Melvin-CnC, you accidentally edited the /docs/cse/index.md file instead of the /docs/cse/administration/index.md file. You'll need to put the /docs/cse/index.md file back to the way it was before, and make your new changes to the /docs/cse/administration/index.md file.

**Review by kimsauce — APPROVED** [review]

**Review by jpipkin1 — APPROVED** [review]
Looks great, @kimsauce! Approved.

By the way, I added commit "[Update card order in index.md](https://github.com/SumoLogic/sumologic-documentation/pull/2445/commits/904e4ca673be19e06392d0ee20837726e865df8a)" to adjust the card order in the /docs/cse/index.md file.

**Comment by Melvin-CnC** [comment]
> @Melvin-CnC, you accidentally edited the /docs/cse/index.md file instead of the /docs/cse/administration/index.md file. You'll need to put the /docs/cse/index.md file back to the way it was before, and make your new changes to the /docs/cse/administration/index.md file.

Sorry about this John. Should've double-checked to be sure. 
Thanks for correcting my mistake, @kimsauce

**Comment by jpipkin1** [comment]
No worries, @Melvin-CnC! I make mistakes all the time that @kimsauce finds when she does reviews.

**Pull request merged**
