### PR TITLE
Revert "Create 2023-11-27-AWSO-logs-for-m&t (#3339)"

### PR DESCRIPTION
**Pull request by jpipkin1**
This reverts commit 72366c7e67df619b0943411c6400647fdae2ed98.

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [x] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request reverts PR #3339. 

This revert is to solve a problem with search not working as [reported in the #dochub Slack channel](https://sumologic.slack.com/archives/C0S86TM6K/p1701279501207189). 

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Comment by jpipkin1** [comment]
@stacykor or @kimsauce, could I get your approval of this pull request?

**Review by kimsauce — APPROVED** [review]

**Comment by jpipkin1** [comment]
Thanks, @kimsauce.

**Comment by jpipkin1** [comment]
@kimsauce, during triage of the broken search problem, I found that when I attempted to check out the branch for PR #3339, I got this:
```
jpipkin@jpipkin-mac sumologic-documentation % git checkout angad-logs_for_M&T_aws_release_note
[1] 8795
zsh: command not found: T_aws_release_note
jpipkin@jpipkin-mac sumologic-documentation % error: pathspec 'angad-logs_for_M' did not match any file(s) known to git

[1]  + exit 1     git checkout angad-logs_for_M
```

It appears that GitHub didn't like that ampersand in the branch name. To resubmit the PR, I'll create a new branch without an ampersand in the name.

**Comment by kimsauce** [comment]
> @kimsauce, during triage of the broken search problem, I found that when I attempted to check out the branch for PR #3339, I got this:
> 
> ```
> jpipkin@jpipkin-mac sumologic-documentation % git checkout angad-logs_for_M&T_aws_release_note
> [1] 8795
> zsh: command not found: T_aws_release_note
> jpipkin@jpipkin-mac sumologic-documentation % error: pathspec 'angad-logs_for_M' did not match any file(s) known to git
> 
> [1]  + exit 1     git checkout angad-logs_for_M
> ```
> 
> It appears that GitHub didn't like that ampersand in the branch name. To resubmit the PR, I'll create a new branch without an ampersand in the name.

Whoa, interesting! that is good to know. Thank you for digging into this.

**Pull request merged**
