### PR TITLE
TRIDENT-16849 - Add a note about scripts

### PR DESCRIPTION
**Pull request by jpipkin1**
## Purpose of this pull request

This pull request (PR) adds a note to the following article:
https://help.sumologic.com/docs/cse/integrations/insight-enrichment-server/#passing-parameters-to-powershell-scripts

Issue number: 
[TRIDENT-16849](https://jasklabs.atlassian.net/browse/TRIDENT-16849)

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Comment by jpipkin1** [comment]
@pkazmir-sumo, could you look at this PR and let me know if you want any changes?

The PR is in draft.

**Comment by pkazmir-sumo** [comment]
I think what you put is good, but we might need to put some text in each section (i.e. CrowdStrike, Greynoise, etc) as readers may just skip to that section.

**Comment by jpipkin1** [comment]
@pkazmir-sumo, I removed the note from the top of the section and instead added a note to each subsection (CarbonBlack, CrowdStrike, GreyNoise, SentinelOne).

**Review by pkazmir-sumo — APPROVED** [review]
lgtm

**Pull request merged**
