### PR TITLE
updates to SUMO-208827

### PR DESCRIPTION
**Pull request by JainM6**
## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ X] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Comment by kimsauce** [comment]
@JainM6 , can you confirm these updates have also been applied on the API Docs side? You can check with [#api-development](https://app.slack.com/client/T024F4SFX/C7C9A0U1Y).

**Review by kimsauce — CHANGES_REQUESTED** [review]
@JainM6 , can you confirm these updates have also been applied on the API Docs side? You can check with [#api-development](https://app.slack.com/client/T024F4SFX/C7C9A0U1Y).

**Review by stacykor — APPROVED** [review]

**Comment by JainM6** [comment]
> @JainM6 , can you confirm these updates have also been applied on the API Docs side? You can check with [#api-development](https://app.slack.com/client/T024F4SFX/C7C9A0U1Y).

@kimsauce This change is done here https://help.sumologic.com/docs/api/search-job/, which is under the API documentation. This has to be applied only on this doc.

**Comment by kimsauce** [comment]
> > @JainM6 , can you confirm these updates have also been applied on the API Docs side? You can check with [#api-development](https://app.slack.com/client/T024F4SFX/C7C9A0U1Y).
> 
> @kimsauce This change is done here https://help.sumologic.com/docs/api/search-job/, which is under the API documentation. This has to be applied only on this doc.

thank you for confirming!

**Pull request merged**
