### PR TITLE
Proposed yarn.lock edits

### PR DESCRIPTION
**Pull request by jpipkin1**
## Purpose of this pull request

This pull request (PR) adds rons4 to the [.clabot](https://github.com/SumoLogic/sumologic-documentation/blob/main/.clabot) file. 

Issue number: For PR #3142 

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Comment by kimsauce** [comment]
Hi @jpipkin1 , thanks for doing! Do you know what might've triggered the yarn lock changes?

**Comment by jpipkin1** [comment]
@kimsauce, I did a fresh "yarn install" in my main branch. Could that have done it?

**Comment by jpipkin1** [comment]
@kimsauce, we could always close this PR without merging it, if that is more comfortable for you.

**Review by kimsauce — APPROVED** [review]

**Review by kimsauce — COMMENTED** [review]
I will test this out!

**Comment by kimsauce** [comment]
I've moved the CLA Bot edit to a [different PR](https://github.com/SumoLogic/sumologic-documentation/pull/3152) so that this one isolates the yarn lock edits.

**Review by kimsauce — CHANGES_REQUESTED** [review]
Kim to test algolia edits

**Review by kimsauce — APPROVED** [review]

**Pull request merged**
