### PR TITLE
CONN-3897 Enable universal connector source with CID 25633

### PR DESCRIPTION
**Pull request by yleiferman**
## Purpose of this pull request

This pull request releases the documentation for the universal connector source. 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

CONN-3897

### CODE REVIEW

**Review by kimsauce — CHANGES_REQUESTED** [review]
Do these need to be changed as well? (see lines 310-311 in send-data/hosted-collectors/cloud-to-cloud-integration-framework/universal-connector-source`) @yleiferman 

Screenshot 2024-11-25 at 3 03 45 PM

**Review by kimsauce — APPROVED** [review]

**Comment by kimsauce** [comment]
@yleiferman , is it ok to merge this?

**Comment by yleiferman** [comment]
Unfortunately no @kimsauce , my PM said to wait until Monday Dec 2nd. I can merge it then.

**Comment by kimsauce** [comment]
> Unfortunately no @kimsauce , my PM said to wait until Monday Dec 2nd. I can merge it then.

No worries! I've added the **do not merge** label.

**Comment by yleiferman** [comment]
Time to GA 👍 .

**Pull request merged**
