### PR TITLE
Create 2024-04-04-content.md

### PR DESCRIPTION
**Pull request by paultobiasumo**
Content release notes update

## Purpose of this pull request

This pull request... updates content release notes for CSIEM on April 4, 2024

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [X] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

N/A

### CODE REVIEW

**Comment by kimsauce** [comment]
Hi @paultobiasumo ! It looks like the file you pushed is empty (file title only). Can you please check this on your end and resubmit? 

Thank you so much for your help with the doc release notes.

**Review by kimsauce — CHANGES_REQUESTED** [review]
File is blank

**Comment by jpipkin1** [comment]
@paultobiasumo, I copied over the [release notes from the Slack announcement](https://sumologic.slack.com/archives/C03ASV6SJV8/p1712260743928099). Let me know if they are good to go.

**Comment by jpipkin1** [comment]
I got approval from @paultobiasumo via Slack.

**Review by jpipkin1 — APPROVED** [review]

**Comment by jpipkin1** [comment]
@kimsauce, I added content to the empty file. It's ready for your review.

**Review by kimsauce — APPROVED** [review]

**Pull request merged**
