### PR TITLE
SUMO-228535 Draft the doc for new ec2 credential archive

### PR DESCRIPTION
**Pull request by yuting-liu**
## Purpose of this pull request

This pull request This is a drafted doc with the roll out of the data archiving using the new type of credential.

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Comment by jpipkin1** [comment]
@yuting-liu, you need to merge the conflicts in your branch before we can review the PR. See the message **This branch has conflicts that must be resolved** above.

**Comment by kimsauce** [comment]
Hi @yuting-liu , I pulled your fork to inspect the merge conflict and it looks like you were using an outdated clone of our site (1,512 commits behind). Can you please sync your fork with our `main` branch and resubmit?

**Comment by kimsauce** [comment]
@yuting-liu Following up on your PR. You've outed an outdated version of our docs repo. The file you edited no longer exists. Please pull the latest version of our repo and resubmit your changes.

Looks like the file you need to edit is probably https://help.sumologic.com/docs/manage/data-archiving/archive

**Review by kimsauce — CHANGES_REQUESTED** [review]
Please pull latest version of our repo and resubmit. I've messaged you in Slack as well.

**Comment by kimsauce** [comment]
Hi @yuting-liu , as we've not heard back from you, I'm closing this out and submitting your changes in a fresh PR [here](https://github.com/SumoLogic/sumologic-documentation/pull/3423).

**Pull request closed without merging**
