### PR TITLE
Group or Aggregate Operators index page

### PR DESCRIPTION
**Pull request by Melvin-CnC**
Edited the app details for the index page as per the Open Source Docs Migration Plan.

## Purpose of this pull request - changes to Group or Aggregate Operators index page

This pull request (PR) ... changes to the Group or Aggregate Operators index page

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by kimsauce — CHANGES_REQUESTED** [review]
Can you put the base URL line at the top of the doc?

`import useBaseUrl from '@docusaurus/useBaseUrl';`

**Comment by kimsauce** [comment]
@Melvin-CnC Hope it's ok - I've changed the title from "Edited app details for the Group or Aggregate Operators index page" to "Group or Aggregate Operators index page" to make it easier to skim, and there are no apps.

**Comment by Melvin-CnC** [comment]
@kimsauce No problem. Anything that makes it easier or helpful, is ok.

**Comment by kimsauce** [comment]
@Melvin-CnC The layout came through as corrupt for me. Can you look at the image that you see in your localhost?

**Review by kimsauce — CHANGES_REQUESTED** [review]
Layout is broken on my end

**Comment by kimsauce** [comment]
Screenshot 2023-03-31 at 1 48 38 PM

**Review by kimsauce — APPROVED** [review]

**Pull request merged**
