### PR TITLE
Split Dashboards and Alerts in nav/dropdown

### PR DESCRIPTION
**Pull request by jpipkin1**
## Purpose of this pull request

This pull request (PR) fixes the "Dashboards" link in the Guides dropdown menu.

Issue number: GitHub issue #2766 

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Comment by jpipkin1** [comment]
Hey @kimsauce, could you take a look at this one? I made an update to the Guides dropdown menu, and I want to make sure I got it right.

**Comment by kimsauce** [comment]
Hi @jpipkin1 , I had a conversation with @stacykor about this earlier this year. She said that Alerts and Dashboards were placed together under the same root page by SME request. Can we put this on hold while I check with the Alerts and Dashboards team?

**Comment by jpipkin1** [comment]
@kimsauce, then maybe we should change the dropdown menu to have an entry for "Dashboards and alerts".

**Comment by jpipkin1** [comment]
@kimsauce, what do you think about my placing alerts and dashboards in the same dropdown menu item?

**Comment by jpipkin1** [comment]
Yes, maybe it is time to separate them at the root, @kimsauce. Is that something you want to do, or should I do it with this ticket?

**Review by kimsauce — APPROVED** [review]

**Comment by kimsauce** [comment]
> Yes, maybe it is time to separate them at the root, @kimsauce. Is that something you want to do, or should I do it with this ticket?

Done! I've messaged the SMEs privately about this to discuss.

**Comment by jpipkin1** [comment]
That's great, @kimsauce! Thanks for fixing it.

**Pull request merged**
