### PR TITLE
Remove beta from transformation Rules API

### PR DESCRIPTION
**Pull request by sukhhanda1**
## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Comment by jpipkin1** [comment]
@sukhhanda1, should we go ahead and publish this PR?

**Comment by sukhhanda1** [comment]
> @sukhhanda1, should we go ahead and publish this PR?

Not yet, I first need to merge the changes in the API docs. The PR is raised and once that change reaches production, I will merge this PR.

**Comment by jpipkin1** [comment]
@sukhhanda1, I added the "Do not merge" label. That tells us not to merge the PR until it's ready.

**Comment by kimsauce** [comment]
Pinged the [Slack thread about this change](https://sumologic.slack.com/archives/C0LKA5BGS/p1729185344040439)

**Comment by sukhhanda1** [comment]
API Docs changes are rolled out everywhere except https://api.sumologic.com/docs/#tag/transformationRuleManagement and https://api.us2.sumologic.com/docs/#tag/transformationRuleManagement.

**Comment by kimsauce** [comment]
> API Docs changes are rolled out everywhere except https://api.sumologic.com/docs/#tag/transformationRuleManagement and https://api.us2.sumologic.com/docs/#tag/transformationRuleManagement.

@sukhhanda1 thanks for the update! To confirm, it still needs to stay on hold?

**Comment by sukhhanda1** [comment]
> > API Docs changes are rolled out everywhere except https://api.sumologic.com/docs/#tag/transformationRuleManagement and https://api.us2.sumologic.com/docs/#tag/transformationRuleManagement.
> 
> @sukhhanda1 thanks for the update! To confirm, it still needs to stay on hold?

@kimsauce yes

**Comment by sukhhanda1** [comment]
https://api.sumologic.com/docs/#tag/transformationRuleManagement is updated and https://api.us2.sumologic.com/docs/#tag/transformationRuleManagement will also get updated in a day or 2. I believe we can merge this public docs as well.

**Comment by sukhhanda1** [comment]
@kimsauce are we good to merge this PR?

**Pull request merged**
