### PR TITLE
Fix regex in processing rule for zscaler-private-access.md

### PR DESCRIPTION
**Pull request by gab-gabriel**
## Purpose of this pull request

Without this change the regex will fail to match the `<165>1 - - - - - - <>` that shows up in the logs being sent to the syslog collector.

## Select the type of change

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Comment by kimsauce** [comment]
Hi @gab-gabriel , thank you for your contribution! Can you please sign our CLA using a valid business email address? This information is kept private.

**Comment by kimsauce** [comment]
moved to https://github.com/SumoLogic/sumologic-documentation/pull/4208

**Comment by gab-gabriel** [comment]
> Hi @gab-gabriel , thank you for your contribution! Can you please sign our CLA using a valid business email address? This information is kept private.

Yep, signed that right after I opened the PR

**Comment by kimsauce** [comment]
> > Hi @gab-gabriel , thank you for your contribution! Can you please sign our CLA using a valid business email address? This information is kept private.
> 
> Yep, signed that right after I opened the PR

To clarify, the business email address you provided came up as invalid

**Comment by gab-gabriel** [comment]
I wonder what criteria defines a "valid" "business email" lol. Anyway tho, I guess its moot since my commit was taken out in favor of #4208 either way

**Pull request closed without merging**
