### PR TITLE
fix position of docker stats source in send-data/use-json-configure-s…

### PR DESCRIPTION
**Pull request by aboguszewski-sumo**
## Purpose of this pull request

This source is in table for log sources, but in fact it is a metric source.

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by stacykor — APPROVED** [review]
LGTM

**Review by JainM6 — APPROVED** [review]
LTGM

**Comment by aboguszewski-sumo** [comment]
@JainM6 I have signed it two times already. I have signed it third time now, with my GitHub username as "Name".

**Comment by JainM6** [comment]
@aboguszewski-sumo : I have added your id to the cla bot. It's merged.

**Pull request merged**
