### PR TITLE
Helm chart v4 update

### PR DESCRIPTION
**Pull request by kimsauce**
## Purpose of this pull request

This pull request updates helm chart v3 to v4.

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Comment by jpipkin1** [comment]
@kimsauce, I'm confused by the new diagram. I think it needs to be redone. The [old diagram](https://help.sumologic.com/docs/observability/kubernetes/collection-setup/) showed everything flowing to Collection, then Enrichment, and then on to Sumo Logic:
K8s-architecture-8875729b8d4b74042dfe4ebe753a8c60

The new diagram seems off. There are extra lines so that Collection is no longer centered over its column, and there is no longer a box under the Enrichment column, but only the heading. 
K8s-architecture-4ffc2fa89339a9ac27257631a9b05bd7

**Comment by jpipkin1** [comment]
@kimsauce, thanks for posting the question in the [#opensource-collection ](https://sumologic.slack.com/archives/C01D3SJQTK3/p1697666160265739?thread_ts=1692687885.510589&cid=C01D3SJQTK3) channel. Let's see what Melissa Sussman says.

**Comment by kimsauce** [comment]
> @kimsauce, thanks for posting the question in the [#opensource-collection ](https://sumologic.slack.com/archives/C01D3SJQTK3/p1697666160265739?thread_ts=1692687885.510589&cid=C01D3SJQTK3) channel. Let's see what Melissa Sussman says.

thank you so much for your attn to detail!

**Comment by kimsauce** [comment]
@jpipkin1 , please see Melissa's response here https://app.asana.com/0/0/1203812552454012/1205763270017169/f

**Comment by ajaiswals** [comment]
@kimsauce @jpipkin1  - My suggestion would be to keep below image.  

This highlights that collection and enrichment is done via OTEL, which we want to highlight upfront. (The extra details for PODs , container names is details on what we enrich which we can keep out from this high level diagram  )

This diagram also keep distinction  for support available on  Falco for collection and enrichment.


Screenshot 2023-10-20 at 11 11 08 AM

**Review by jpipkin1 — APPROVED** [review]

**Pull request merged**
