### PR TITLE
Update metric-query-error-messages.md for Datapoints limit release

### PR DESCRIPTION
**Pull request by zjiawei3**
## Purpose of this pull request

This pull request (PR) updates the error messages with Datapoints limit feature. Design 
https://docs.google.com/document/d/1kbiba7lzliFlHbpYABkvuH4XOmx2mblqC1c0dDVEsFg/edit# 

Issue number: 
https://jira.kumoroku.com/jira/browse/MET-17346

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Comment by kimsauce** [comment]
@zjiawei3 , thanks for your submission! Please [sign the CLA](https://github.com/SumoLogic/sumologic-documentation/pull/781#issuecomment-1294238550) when you can and we'll review your request.

**Comment by zjiawei3** [comment]
Signed. Thanks!

**Comment by kimsauce** [comment]
@zjiawei3 thank you for signing the CLA so quickly! I've added you as a contributor. Could you please sync your fork with our repo and try pushing again? Then it will allow you to merge.

**Review by kimsauce — APPROVED** [review]

**Comment by zjiawei3** [comment]
Hi @kimsauce , sorry to bother you but this PR is not meant to be merged now. We would like to coordinate the release of this doc with the feature release, and merge this right after the feature is enabled in prods. Could you help grant me permission so I could perform the merge once needed? Thanks.

**Comment by zjiawei3** [comment]
https://jira.kumoroku.com/jira/browse/SUMO-201970 is the SCR to rollout this feature. We will attach this PR to the SCR for approval.

**Comment by kimsauce** [comment]
> Hi @kimsauce , sorry to bother you but this PR is not meant to be merged now. We would like to coordinate the release of this doc with the feature release, and merge this right after the feature is enabled in prods. Could you help grant me permission so I could perform the merge once needed? Thanks.

Thank you for the heads up! Just added the "do not merge" label. You're approved as a contributor, so you can merge when you are ready.

**Comment by zjiawei3** [comment]
Thanks Kim, but I still see the following lines instead of the merge button:

This pull request can be automatically merged by project collaborators
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by zjiawei3** [comment]
@MariePMcGarry it is supposed to be merged after the feature is enabled.. That's why Im asking for the write access.

**Comment by kimsauce** [comment]
@MariePMcGarry per @zjiawei3 's comment, this should not have been merged. Reverting this PR now.

**Comment by MariePMcGarry** [comment]
Sorry. I'm a menace.

**Comment by zjiawei3** [comment]
@kimsauce @MariePMcGarry Let me create a new branch and PR to attach to the SCR, and file for approval immediately. Can one of you help grant me permission to merge the PR? Thanks.

**Comment by zjiawei3** [comment]
> > @kimsauce @MariePMcGarry Let me create a new branch and PR to attach to the SCR, and file for approval immediately. Can one of you help grant me permission to merge the PR? Thanks.
> 
> Can you check your email for an invite? Granted you write access, so you should be good to go.

Thanks Kim, Im now able to see the buttons for adding labels and merge.

**Pull request merged**
