### PR TITLE
Added Azure eventhub c2c migration

### PR DESCRIPTION
**Pull request by JainM6**
## Purpose of this pull request

Updated a few links in azure-event-hubs-source.md
Added event-hub-cloud-to-cloud-source-migration.md

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by kimsauce — DISMISSED** [review]
It looks like one photo was imported twice under different names: `static/img/send-data/unnamed.png` and `static/img/send-data/unnamed (1).png`

**Comment by kimsauce** [comment]
Thanks, @JainM6 ! It looks like the images are pixelated. Can you or your SME provide a high-res version?

**Review by kimsauce — CHANGES_REQUESTED** [review]
Hi Megha, do you have more high-res screenshots? These are fuzzy and hard to read.

**Comment by JainM6** [comment]
> Hi Megha, do you have more high-res screenshots? These are fuzzy and hard to read.

@kimsauce: Yes, this was already communicated to SME on Monday. I should get the images today.

**Pull request closed without merging**
