### PR TITLE
Amazon/AWS apps ABC sort order

### PR DESCRIPTION
**Pull request by kimsauce**
## Purpose of this pull request

Re-sorted Amazon/AWS apps in alphabetical order (sidebars only)

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by jpipkin1 — CHANGES_REQUESTED** [review]
@kimsauce, when I run yarn and view the left nav, some items are not in alphabetical order. Could you take a look?

**Comment by kimsauce** [comment]
> when I run yarn and view the left nav, some items are not in alphabetical order. Could you take a look?

good catch, @jpipkin1

**Review by jpipkin1 — APPROVED** [review]
@kimsauce, I'll go ahead and approve, since I know you want to move ahead with this PR. But I'd like to meet with you briefly to go over our strategy for alphabetizing apps in the left nav.

**Comment by kimsauce** [comment]
> @kimsauce, I'll go ahead and approve, since I know you want to move ahead with this PR. But I'd like to meet with you briefly to go over our strategy for alphabetizing apps in the left nav.

Sure thing, I'll add it agenda for tmr

**Pull request merged**
