### PR TITLE
Fix rendering of tables in metric-histograms.md

### PR DESCRIPTION
**Pull request by bchrobot-mh**
## Purpose of this pull request

This pull request fixes broken table rendering in `metric-histograms.md` by fixing table markdown syntax.

## Select the type of change

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

N/A

### CODE REVIEW

**Comment by kimsauce** [comment]
Thanks @bchrobot-mh so much for submitting this! Please [sign our CLA](https://docs.google.com/forms/d/e/1FAIpQLScRonzY0gLo7swLExL8CeLLNvdvEkRtIjJLUrFalo0vaAdp7g/viewform) when you get a chance and we'll review/approve your PR.

**Comment by bchrobot-mh** [comment]
> Thanks @bchrobot-mh so much for submitting this! Please [sign our CLA](https://docs.google.com/forms/d/e/1FAIpQLScRonzY0gLo7swLExL8CeLLNvdvEkRtIjJLUrFalo0vaAdp7g/viewform) when you get a chance and we'll review/approve your PR.

Signed!

**Review by kimsauce — APPROVED** [review]
@bchrobot-mh , approved! Many thanks for taking the time to fix this! Appreciate your help.

**Comment by kimsauce** [comment]
Note: I've applied further needed style/formatting fixes in this commit: https://github.com/SumoLogic/sumologic-documentation/pull/4297/commits/2ec5de5404b5dfbab97f7fde0aaff568e3b02476

**Pull request merged**
