### PR TITLE
Update network-sensor-deployment-guide.md

### PR DESCRIPTION
**Pull request by vkvbit**
invalid package name
python36 is not a package. I should be python3

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [x] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Comment by vkvbit** [comment]
> Thank you for your contribution! As this is an open source project, we require contributors to sign our Contributor License Agreement and do not have yours on file. To proceed with your PR, please [sign your name here](https://forms.gle/YgLddrckeJaCdZYA6) and we'll add you to our approved list of contributors.

Done

**Comment by jpipkin1** [comment]
@vkvbit, thank you for finding that typo.

**Comment by jpipkin1** [comment]
I sent a request to a developer to verify that this is a needed update.

**Comment by jpipkin1** [comment]
Closing this PR because the fix will be done with PR #3717.

**Pull request closed without merging**
