### PR TITLE
Create 2023-01-05-content.md

### PR DESCRIPTION
**Pull request by PaulTobia**
## Purpose of this pull request

This pull request (PR) ...
Update CSE release notes for 1/5/2023

Issue number: 

N/A

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [X] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by kimsauce — DISMISSED** [review]
Date needs to be today, Jan 6, or will not go out in RSS feed.

**Comment by PaulTobia** [comment]
RSS not necessary

**Comment by kimsauce** [comment]
@PaulTobia , we have your GitHub username in our CLA as **ptobia**. Should we replace with the one you used here?

**Comment by PaulTobia** [comment]
Apologies I accidentally switched accounts. Please keep ptobia as the Sumo account.

**Review by MariePMcGarry — APPROVED** [review]

**Review by MariePMcGarry — APPROVED** [review]

**Review by stacykor — APPROVED** [review]

**Comment by kimsauce** [comment]
@PaulTobia since everything is approved, can you please merge on your end? We can't do this on our end since the PR originated from your fork.

**Pull request closed without merging**
