### PR TITLE
CONN-1555: Simplify Sidebar Creation

### PR DESCRIPTION
**Pull request by yleiferman**
## Purpose of this pull request

This pull request (PR) simplifies the generation of sidebar items to prevent forgetting new items

Issue number: 

CONN-1555 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [x] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by jpipkin1 — CHANGES_REQUESTED** [review]
@yleiferman, this is a cool solution! However, when I ran yarn to view the autogenerated sidebar in my local environment, I saw that "Cloud-to-Cloud Integration Framework Sources" appeared in the middle of the sidebar section. So something is amiss. 

Screenshot 2023-07-26 at 1 55 13 PM

**Comment by jpipkin1** [comment]
@kimsauce, as cool an an autogenerated sidebar is, it would do nothing to generate cards for the hub pages. So I'm not sure we'd want to implement it. However, personally, I could do without having to maintain the cards.

**Comment by jpipkin1** [comment]
@kimsauce, do we still want to consider this autogeneration method for selected sections? Or did we decide as a doc team that we want to continue doing the sidebar manually for all sections?

**Comment by kimsauce** [comment]
Hi Yair, while we appreciate your idea and hard work putting this together, we've decided against automating sidebars. If you have any Qs, please reach out to us on dochub.

**Pull request closed without merging**
