### PR TITLE
Collect Metrics Telegraf index page

### PR DESCRIPTION
**Pull request by Melvin-CnC**
## Purpose of this pull request

This pull request (PR) for making changes to the Telegraf index page as per the Open Source Docs Migration Plan.

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

### CODE REVIEW

**Review by kimsauce — CHANGES_REQUESTED** [review]
Can you move the image to the /send-data image folder? The /icons folder is reserved for Sumo Logic-branded icons.

**Comment by Melvin-CnC** [comment]
> 

Thanks, edited the image folder location.

**Comment by Melvin-CnC** [comment]
> > 
> 
> Thanks, edited the image folder location.

@kimsauce

**Comment by kimsauce** [comment]
> > > 
> > 
> > 
> > Thanks, edited the image folder location.
> 
> @kimsauce

You still need to move the image @Melvin-CnC 

Screenshot 2023-04-17 at 11 35 29 AM

**Review by kimsauce — CHANGES_REQUESTED** [review]
Please move the image to correct folder

**Pull request merged**
