### PR TITLE
Broken asterisk formatting

### PR DESCRIPTION
**Pull request by kimsauce**
## Purpose of this pull request

This pull request fixes Broken asterisk formatting

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

### CODE REVIEW

**Comment by jpipkin1** [comment]
@kimsauce, I'm reviewing this PR now, and am finding more asterisk formatting to clean up. I'll submit a commit when I'm done.

**Review by jpipkin1 — APPROVED** [review]
@kimsauce, I found a lot more broken asterisk formatting in the files in this PR (see commit "[Fix more asterisk problems](https://github.com/SumoLogic/sumologic-documentation/pull/3521/commits/632643fcfc0ef45bc045d9e694439e8e541a26ba)"). It looks like you only searched for one type of broken asterisk formatting, when there are more.

**Comment by jpipkin1** [comment]
@kimsauce, besides asterisk formatting problems, I'm also seeing indenting issues since we upgraded to Docusaurus version 3. We may need to do some cleanup for it.

**Comment by kimsauce** [comment]
> @kimsauce, I found a lot more broken asterisk formatting in the files in this PR (see commit "[Fix more asterisk problems](https://github.com/SumoLogic/sumologic-documentation/pull/3521/commits/632643fcfc0ef45bc045d9e694439e8e541a26ba)"). It looks like you only searched for one pattern of broken asterisk formatting, when there are more.

thank you so much, John!!

**Pull request merged**
